version: '3.3'

services:

  restapi:
    container_name: restapi
    build:
      dockerfile: restapi.dockerfile
      context: ./restapi
    volumes:
      - ./restapi:/code
    ports:
      - "5555:5555"

  client:
    container_name: client
    build:
      dockerfile: client.dockerfile
      context: ./client
    volumes:
      - ./client:/application
    tty: true
    links:
      - restapi

  server:
    container_name: server
    build:
      dockerfile: server.dockerfile
      context: ./server
    volumes:
      - ./server:/application
    links:
      - restapi
    ports:
      - "3333:3333"